# INPUT
#auto_userdots_folder: "/media/MiSo/iFISH-singleLocus-analysis/input/auto_userdots"
#auto_userdots_folder: "/media/MiSo/iFISH-singleLocus-DOTTER/output/auto_userdots"
auto_userdots_folder: "/media/MiSo/iFISH-singleLocus-DOTTER/output/auto_userdots_CAc"
deconvolved_root_folder: "/media/MiSo/iFISH-singleLocus-analysis/input/decon"
metadata: "/media/MiSo/iFISH-singleLocus-analysis/input/2018-09-13-iFISH-singleLocus-metadata.tsv"

# OUTPUT
masks_root_folder: "/media/MiSo/iFISH-singleLocus-analysis/input/cmask" # set to None to avoid storing the segmentation output
#output_root_folder: "/media/MiSo/iFISH-singleLocus-analysis/output"
#output_root_folder: "/media/MiSo/iFISH-singleLocus-DOTTER/output/iFISH-singLoc-snakemake-rootOutput-preFitting"
output_root_folder: "/media/MiSo/iFISH-singleLocus-DOTTER/output/iFISH-singLoc-snakemake-rootOutput-CAcorrected-preFitting"

# GENERAL
aspect: [300., 130., 130.]

# LAMINA DISTANCE
dilation: 5
distance_type: "center_percentile"
threads_per_job: 10
mask_prefix: "cmask_"
mask_compressed: True
mask_labeled: False
axis_fraction: 0.25
discard_channels: ["a700", "ir800"]
dilate_Z: True

# MERGE & FILTERS
metadata_delim: "\t"
k_sigma_population_selection: 3
ndots:
  HAP1: 1
  IMR90: 2
  HeLa: 4
dot_value_column_label: "pixel"

# PLOTS
giemsa_path: "/media/MiSo/iFISH-singleLocus-analysis/input/hg19.giemsa_bands.bed"
probe_path: "/media/MiSo/iFISH-singleLocus-analysis/input/tda_dna-unifish_oligopool_chr_spotting.bed"

# RANKS
rank_bin_sizes: [ 100000, 1000000, 10000000 ]
probe_bed:
  1Mbprobe: "/media/MiSo/iFISH-singleLocus-analysis/input/tda_dna-unifish_oligopool_chr_spotting.size1Mbp.bed"
  1Mbprobe.transCorrected.HAP1.Philadelphia: "/media/MiSo/iFISH-singleLocus-analysis/input/tda_dna-unifish_oligopool_chr_spotting.size1Mbp.transCorrected.HAP1.Philadelphia.bed"

# SAMPLES
datasets: [
  "iAM102_20180607_001",
  "iAM105_20180615_001",
  "iAM114_20180628_001",
  "iAM118_20180704_001",
  "iAM120_20180706_001",
  "iAM121_20180706_001",
  "iAM122_20180706_001",
  "iAM124_20180709_001",
  "iAM142_20180720_001",
  "iAM143_20180720_001",
  "iAM145_20180723_001",
  "iAM145_20180723_002",
  "iAM147_20180725_001",
  "iAM152_20180730_001",
  "iAM154_20180730_001",
  "iAM155_20180731_001",
  "iAM155_20180731_002",
  "iAM156_20180731_001",
  "iAM158_20180801_001",
  "iAM160_20180806_001",
  "iAM161_20180807_001",
  "iAM163_20180808_001",
  "iAM163_20180808_002",
  "iAM164_20180808_001",
  "iAM169_20180813_001",
  "iAM170_20180813_001",
  "iAM178_20180822_001",
  "iAM178_20180822_002",
  "iAM180_20180822_001",
  "iAM180_20180822_002",
  "iAM181_20180823_001",
  "iAM181_20180823_002",
  "iAM182_20180823_001",
  "iAM185_20180824_001",
  "iAM185_20180824_002",
  "iAM186_20180824_001",
  "iAM188_20180827_001",
  "iAM189_20180827_001",
  "iAM191_20180828_001",
  "iAM192_20180828_001",
  "iAM193_20180829_001",
  "iAM193_20180829_002",
  "iAM195_20180830_001",
  "iAM195_20180830_002",
  "iAM196_20180830_001",
  "iAM196_20180830_002",
  "iAM197_20180830_001",
  "iAM199_20180831_001",
  "iAM200_20180831_001",
  "iAM201_20180903_001",
  "iAM203_20180904_001",
  "iAM204_20180904_001",
  "iAM206_20180906_001",
  "iAM206_20180906_002",
  "iAM207_20180906_001",
  "iJC808_20170906_001",
  "iJC809_20170906_001",
  "iJC810_20170906_001",
  "iJC816_20170911_001",
  "iJC843_20170926_001",
  "iJC845_20170927_001",
  "iJC852_20171004_001",
  "iJC853_20171004_001",
  "iJC855_20171004_001",
  "iJC856_20171004_001",
  "iJC857_20171004_001",
  "iJC858_20171004_001",
  "iJC859_20171004_001",
  "iJC860_20171006_001",
  "iJC861_20171006_001",
  "iJC872_20171012_001",
  "iJC876_20171105_001",
  "iJC888_20171108_001",
  "iJC894_20171114_001",
  "iJC895_20171114_001",
  "iJC896_20171116_001",
  "iJC897_20171116_001",
  "iJC898_20171116_001",
  "iJC899_20171120_001",
  "iJC901_20171120_001",
  "iJC902_20171121_001",
  "iJC903_20171122_001",
  "iJC904_20171122_001",
  "iJC906_20171122_001",
  "iJC907_20171122_001"
]